version: '3'

services:
  django:
    image: back-end-app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./soft_serve:/soft_serve
    ports:
      - 8000:8000
