version: '3'

services:
  backend:
    build:
      context: .
    restart: unless-stopped
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/soft_serve
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  s3:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=appelsin
    env_file:
      - .env.dev

volumes:
  minio_data:
