version: '3'

services:
  backend:
    build:
      context: .
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/soft_serve
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
