---
name: Build and Deploy

on:
  # pull_request:
  push:
    branches:
      # - "main"
      - "stage"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: 2xnone/appelsin-be:${{ steps.vars.outputs.sha_short }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    container:
      image: 2xnone/deployer:sha-f88e0c4
      env:
        DEPLOY_KEY: /root/.ssh/deployment
        REPO: git@github.com:softserve-appelsin/infra.git
        REVISION: main
        KEY: image.tag
        # VALUE: 
        FILE: apps/be/stage.yaml
        GIT_USERNAME: dnull-bot
        GIT_EMAIL: shellshock.dnull+bot@gmail.com
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.INFRA_KEY }}
          name: deployment
          known_hosts: unnecessary
      - name: Commit to infra repo
        run: |
          /app/deployer  \
          -f "apps/be/stage.yaml" \
          -k "image.tag" \
          -v "${{ steps.vars.outputs.sha_short }}"
