---
name: Build and Publish

on:
  pull_request:
  push:
    branches:
      - "main"
      - "stage"

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: 2xnone/appelsin-be
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish-docker-image
    container:
      image: 2xnone/deployer:sha-f88e0c4
      env:
        DEPLOY_KEY: /ssh/infra
        REPO: git@github.com:softserve-appelsin/infra.git
        REVISION: main
        KEY: image.tag'
        VALUE: ${{ needs.build.outputs.tag }}
        FILE: apps/be/stage.yaml
        GIT_USERNAME: dnull-bot
        GIT_EMAIL: shellshock.dnull+bot@gmail.com
    steps:
      - name: Commit to infra repo
        run: |
          /app/deployer  \
          -f "apps/be/stage.yaml" \
          -k "image.tag" \
          -v "${{ needs.build.outputs.tag }}"
